import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'
import Instagram from '../components/Instagram'
import Slider from '../components/Slider'
import { SliderData } from '../components/SliderData'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Pixter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero 
        heading='Buy or Sell web apps' message='Browse our categories and purchase a web app, or sell your own apps.' 
      />
      <Slider slides={SliderData} />
      <Instagram />
    </div>
  )
}
